name: Build EpiData Maven Parent Pom

on: 
  pull_request:
    branches: 
      - master

env:
  PARENT_VERSION: "1.0"

jobs:
  all:
    name: Build Parent
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Update Version
        run: mvn versions:set -DnewVersion=$PARENT_VERSION.$GITHUB_RUN_NUMBER-SNAPSHOT

      - name: Deploy
        run: mvn clean deploy